services:
  nginx:
    image: nginx:stable-alpine
    container_name: wolf_shop_nginx
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wolf-shop
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:8
    container_name: wolf_shop_mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wolf-shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wolf-shop

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: wolf_shop_php
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - wolf-shop

networks:
  wolf-shop:
    driver: bridge
